#!/usr/bin/env bash
file="$1"
user="$3"
ip="$2"
privatekeyPath="$4"

if (("$#" == 4))
then
    scp -i "$privateKeyPath" "$file" "$user"@"$ip":~/
elif (("$#" == 3))
then
    scp "$file" "$user"@"$ip":~/
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY">&2
fi
