#!/usr/bin/env bash
# This script is installing Nginx web server on my server

# Update the package list
apt-get update

# Install Nginx
apt-get install -y nginx

# Ensure Nginx is running
service nginx start

#configure server to allow request from port 8
ufw allow 'Nginx Http'

# Create a new index.html with "Hello World!" content
echo 'Hello World!' > sudo tee /var/www/html/index.html

