#!/usr/bin/env bash
# Installs Nginx on a web server and configures it such that /redirect_me is redirecting to another page

# Get package updates
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Configure Nginx to listen on port 80
sudo ufw allow 'Nginx HTTP'

# Configure Nginx to serve a page which displays 'Hello World!' when it receives a GET request
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Initiate redirection
sudo bash -c 'cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80;
    server_name 164.92.196.206;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF'

# Restart Nginx
sudo service nginx restart