#!/usr/bin/env bash
# Installs Nginx on a web server and configures it such that /redirect_me is redirecting to another page

# Get package updates
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Configure Nginx to listen on port 80
sudo ufw allow 'Nginx HTTP'

# Configure Nginx to serve a page which displays 'Hello World!' when it receives a GET request
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Initiate redirection
sudo sed -i '/^server {/a \    location \/redirect_me {\n        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart