#!/usr/bin/env bash
# Installs Nginx on a web server and configures it such that a custom 404 error page is displayed when aresource is not found

# Get package updates
#sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Configure Nginx to listen on port 80
sudo ufw allow 'Nginx HTTP'

# Configure Nginx to serve a page which displays 'Hello World!' when it receives a GET request
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Set up redirection on /redirect_me
rewrite_directive="\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/server_name _/a\ $rewrite_directive" /etc/nginx/sites-available/default

# Create custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Direct 404 Errors to custom page
error_directive="\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "/rewrite/a\ $error_directive" /etc/nginx/sites-available/default

# Awk -i option not available on all versions of awk
#sudo awk -i inplace -v string_to_replace="$string" '/rewrite/ {print; print string_to_replace; next} 1' config

# Restart Nginx
sudo service nginx restart