#!/usr/bin/env bash
# This script handles signals by running a process and controlling
# how the process communicate with signals and also
# creating and deleting a file

sigterm_manager()
{
	echo "I hate the kill command"
	sigquit_manager
}

sigint_manager()
{
	echo "Y U no love me?!"
}

sigquit_manager()
{
	rm -f /var/run/myscript.pid
	exit
}

trap sigterm_manager SIGTERM
trap sigint_manager SIGINT
trap sigquit_manager SIGQUIT

echo $$ > /var/run/myscript.pid
while true; do
    echo "To infinity and beyond"
    sleep 2
done
