#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# and Badluck at the 4th iteration, Goodluck at 8th iteration

i=1

while ((i<=10))
do
	if ((i==4))
	then
		echo "bad luck"

	elif ((i==8))
	then
		echo "good luck"

	else
		echo "Best School"
	fi
	((i++))
done
