#!/usr/bin/env bash
# This script displays the content of the current directory
# In a list format where only the part of the name 
# after the first dash is displayed

for content in *
do
	echo "$content" | cut -d '-' -f 2
done
